### ISSUE TITLE
Design new placeholder.png

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#14]
A call for a designer to change the theme placeholder (placeholder.png) as it looks pretty boring.

**placeholder.png (current)**
![screenshot](https://cloud.githubusercontent.com/assets/8960296/18906863/331abe70-8561-11e6-864c-8491dbeb05ec.png)

**Comment by JonathanSpeek** [comment]
I can take this one, where would you like me put the placeholder.png in your repo?

**Comment by pjhampton** [comment]
Closed via #16
