### ISSUE TITLE
Post Format Development (aside)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#18]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - gallery
 - link
 - image
 - ~~quote~~ - COMPLETE
 - status
 - video
 - audio
 - chat

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-aside.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> aside - Typically styled without a title. Similar to a Facebook note update.

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by RickBakkr** [comment]
Although I am not really experienced with Wordpress yet, wouldn't it be nice to give this one a shot in the context of Hacktoberfest? Can I claim it, @pjhampton ?

**Comment by pjhampton** [comment]
Of course you can @RickBakkr 💙  💛  ❤️ 
I can mentor you through it if need be. Just ping me if you have any questions.

Here is a picture of an aside: http://justintadlock.com/blog/wp-content/uploads/2012/09/aside-matt.png

**Comment by RickBakkr** [comment]
Thanks for your immense positive response.

Can you give me a little example of how you imagine the aside post in Bootstrap?

**Comment by pjhampton** [comment]
To be honest, I see this it as a fairly minor change. This is because someone adopting this theme to build their own will probably change it to suit their design needs. Maybe consider just putting a border around the main content on the page?

Kind of like what @Bobeta did in #39

After all, it up to you to make it your own 😄  You can get as creative as you want, but my advice is keep it simple! ✨

**Comment by RickBakkr** [comment]
Ahh, I see. I will hopefully have time to pick this up tomorrow. Sorry for letting you wait haha

**Comment by pjhampton** [comment]
haha, no need to apologize @RickBakkr!! I REALLY appreciate the contribution 😄  
Take your time and let me know if you have any issues. I will be happy to help!

**Comment by RickBakkr** [comment]
Although it looks and is simple, it might just do the trick: adding a Blockquote. I thought this would be appropriate since I think you would use an Aside for posts like quotes. If you agree, I will send in an PR, let me know what you think!

Example: 
![Example](http://i.imgur.com/rrqMGXQ.png)

**Comment by pjhampton** [comment]
Yep, this looks good. BUT, there is a post format called quote already. I think we need to differentiate it some how, like give it a class of `<blockquote class="aside">...` and give it a different background color other than grey. What do you think @RickBakkr? 😄

**Comment by RickBakkr** [comment]
Tried to play around a little with the card-design known from Material to give it a different look. What do you think about this idea, @pjhampton ? 

Example:
![Example](http://i.imgur.com/COzzGzP.png)

**Comment by pjhampton** [comment]
Yeah, this looks pretty slick @RickBakkr 👍 
Look forward to the PR 😄

**Comment by RickBakkr** [comment]
I love to hear you're positive about my work. The PR is opened :-)
