### ISSUE TITLE
Post Format Development (chat)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#20]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - gallery
 - link
 - image
 - ~~quote~~ - COMPLETE
 - status
 - video
 - audio
 - **chat**

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-chat.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> chat - A chat transcript, like so:
```
John: foo
Mary: bar
John: foo 2
```

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by admah** [comment]
So just to confirm - you want an additional post format called "chat"?

**Comment by marlek** [comment]
I'll take this one

**Comment by pjhampton** [comment]
So much awesome @marlek 💙  💛  ❤️ 

Thanks! Let me know if you have any questions or need any help.
