### ISSUE TITLE
Post Format Development (image)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#23]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - gallery
 - link
 - **image**
 - ~~quote~~ - COMPLETE
 - status
 - video
 - audio
 - chat

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-image.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> **image** - A single image. The first <img /> tag in the post could be considered the image. Alternatively, if the post consists only of a URL, that will be the image URL and the title of the post (post_title) will be the title attribute for the image.

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by fvaneldijk** [comment]
Hi @pjhampton, I would like to claim this issue.

**Comment by pjhampton** [comment]
Thanks @fvaneldijk 😄
