### ISSUE TITLE
Post Format Development (link)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#26]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - gallery
 - **link**
 - image
 - ~~quote~~ - COMPLETE
 - status
 - video
 - audio
 - chat

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-link.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> link - A link to another site. Themes may wish to use the first `<a href=””>` tag in the post content as the external link for that post. An alternative approach could be if the post consists only of a URL, then that will be the URL and the title (post_title) will be the name attached to the anchor for it.

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by fvaneldijk** [comment]
Hi @pjhampton, I would like to claim this one as well.

**Comment by pjhampton** [comment]
All yours @fvaneldijk 💛

**Comment by pjhampton** [comment]
Hey @fvaneldijk. How are you getting on with this? 😄

**Comment by fvaneldijk** [comment]
Hi @pjhampton, was about to message you to tell you I'll pick this up tomorrow. This week has been chaotic to say the least. Sorry for letting you wait :)

**Comment by pjhampton** [comment]
Hey @fvaneldijk!! No no, don't apologize! I REALLY appreciate your help. Just making sure you hadn't disappeared off the earth 😆 

💛  💙  ❤️  💜  💚
