### ISSUE TITLE
Post Format Development (video)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#27]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - gallery
 - link
 - image
 - ~~quote~~ - COMPLETE
 - status
 - **video**
 - audio
 - chat

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-video.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> video - A single video or video playlist. The first <video /> tag or object/embed in the post content could be considered the video. Alternatively, if the post consists only of a URL, that will be the video URL. May also contain the video as an attachment to the post, if video support is enabled on the blog (like via a plugin).

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by themaxsandelin** [comment]
I would like to take this on! Could you explain in more detail what's to be done? Is it CSS styling of a post type section?

**Comment by pjhampton** [comment]
That would be awesome @themaxsandelin!! 😄 

Yep, so both. You want to add light styling to 
https://github.com/pjhampton/BigBooty/blob/master/static/css/app.css

and alter the templating in:
https://github.com/pjhampton/BigBooty/blob/master/formats/format-video.php

Here is some more information on post formats:
https://www.youtube.com/watch?v=--5I-avZUcY

Let me know if you have any questions and I will help you as much as I can

**Comment by themaxsandelin** [comment]
Thank you very much for the information. Now that I have a better understanding I can say that I would love to take this on! You can assign it to me and I'll take a look at it right now 💪🏻😊

**Comment by themaxsandelin** [comment]
In terms of styling, how much different are you thinking it will be to the general styling of the page? Does text content and images get affected as well or is it just the video embeded in the post?

**Comment by pjhampton** [comment]
Hey @themaxsandelin!!

Because it's a starter theme, please make it as minimal as possible. It should be really basic / plain as the point is the next theme you develop you can restyle it with minimal fuss. I don't believe any content / images should be showing up. You should be taking the title (which the user will supply as a link) and then render it on the front end. 

Does this make sence. So I could create a new video post with the title: https://www.youtube.com/watch?v=G8KpPw303PY

and the video would show up on the page.

Does that help?

**Comment by themaxsandelin** [comment]
Yes, that makes perfect sense! You want the link to parsed, so that depending on what type of link they post they get an embedded player? (ex. YouTube link, Vimeo link or link to .mp4 file)

**Comment by pjhampton** [comment]
You got it @themaxsandelin 👍

**Comment by themaxsandelin** [comment]
@pjhampton Cool. I don't quite understand your file structure in terms of the content formats. Where have you defined the templating for each post type, as `format-video.php` does not seem to be used when I post a video.

**Comment by pjhampton** [comment]
@themaxsandelin 

hmm, it seems I was slightly wrong if you look at this screenshot I just took:

**backend**
![screen shot 2016-10-06 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/8960296/19155559/d5511466-8bd6-11e6-9d0a-a18d6fc6e4fe.png)

**frontend**
![screen shot 2016-10-06 at 3 10 35 pm](https://cloud.githubusercontent.com/assets/8960296/19155630/10dc7c64-8bd7-11e6-9cee-acb2224adc61.png)

The images seem to be showing up anyway which is cool. I suppose it just needs styled. Have you made sure to check the `video` option in the Format box on the right (see screenshot 1)

**Comment by themaxsandelin** [comment]
Oh I see. So the styling is up to me? :)

**Comment by pjhampton** [comment]
Yeah, definitely @themaxsandelin 🎃

**Comment by themaxsandelin** [comment]
@pjhampton I have a hard time seeing how to style the videos. Could you give me some examples of how you imagine it could look like? I'm just thinking about the user's ability to include content next to the videos and so on.

**Comment by pjhampton** [comment]
Hey @themaxsandelin 

Honestly, I don't mind what it looks like. After a web search there I found these three:

http://docs.cmsmasters.net/admin1/wp-content/uploads/sites/2/2013/12/video-post-format.png
https://www.designwall.com/wp-content/uploads/sites/2/2013/12/video-post-format-frontend.png
https://make.wordpress.org/training/files/2014/08/Screen-Shot-2014-08-01-at-2.30.07-PM.png

Does this help you?
