### ISSUE TITLE
Post Format Development (gallery)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#28]
# Welcome 🚀 

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:

 - aside 
 - **gallery**
 - link
 - image
 - ~~quote~~ - COMPLETE
 - status
 - video
 - audio
 - chat

## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-gallery.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> gallery - A gallery of images. Post will likely contain a gallery shortcode and will have image attachments.

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)

## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by RickBakkr** [comment]
Shall I try to do this one too, @pjhampton ?

**Comment by pjhampton** [comment]
If you are up for it @RickBakkr 😄

**Comment by RickBakkr** [comment]
Okay, I'll give it a shot when I have some time in the next few days!

**Comment by RickBakkr** [comment]
What do you think of this, @pjhampton ?
![Example](http://i.imgur.com/RBYJm3F.png)

* Don't mind the example pics and the actual content ;-)

**Comment by pjhampton** [comment]
This looks pretty cool @RickBakkr!! Is it using col-*-* for layout? If so, is it possible we could increase the image size, or is this something that is done within the WordPress crop tool?

😄

**Comment by RickBakkr** [comment]
No, I have mainly editted the default gallery code using CSS. AFAIK you can change the size of the images from within WP, in above image set to "Thumbnail".

**Comment by pjhampton** [comment]
Sure @RickBakkr. If you think that is the best implementation we will go with that 😄  I was just wondering how you approached it. That is fine about the thumbnail sizes!

**Comment by RickBakkr** [comment]
Well, I didn't really see a different way of approaching this... I have enlarged the boxes from 25% (equal to col-md-3) to 33% (col-md-4). I'll do the PR in a few minutes :-)
