### ISSUE TITLE
Move code to different file (Simple Refactor)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#29]
# Welcome 🚀 

In [functions.php](https://github.com/pjhampton/BigBooty/blob/master/functions.php), there are 11 lines of code that shouldn't be there. Lines 59 - 70 should be moved to **config/woocommerce.php**

--
**IMPORTANT**
This issue is reserved for people who **haven't** contributed to this project before. Please comment below to claim it - first come first serve. Happy hacking ❤️

**Comment by pijemcolu** [comment]
woot, I'll happilly claim this. :)

**Comment by Dasio** [comment]
I forget to comment, didnt know how to claim it

**Comment by pjhampton** [comment]
Sorry @Dasio, but fair is fair - I will let @pijemcolu take this forward. However, I believe this still counts if even closed: https://hacktoberfestchecker.herokuapp.com/?username=Dasio
