### ISSUE TITLE
Consider adding an .editorconfig file

### ISSUE THREAD

**Issue by themaxsandelin** [pjhampton/BigBooty#33]
Setting up an [EditorConfig](http://editorconfig.org), particularly in collaboration projects, will let you set a standard for each project in terms of coding style. This makes sure that the indentations are formatted correctly and you are able to define coding style for each language that you use in your project.

All that is needed is an `.editorconfig` file where you specify all of the project rules. The developer then has to install the plugin for his/her editor, unless he/she uses WebStorm or RubyMine for example.

> Check out the [EditorConfig](http://editorconfig.org) website for more info.

**Comment by pjhampton** [comment]
💙  💛 

This looks like a good idea to me. Do you want to take this forward @themaxsandelin
