### ISSUE TITLE
Fix Pagination

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#36]
There is an issue with the styling of the pagination for the posts. We need to fix this because of the doesn't look that great and this is should be provided out of the box for a starter theme.

**How it should look**
![screen shot 2016-10-08 at 8 03 27 pm](https://cloud.githubusercontent.com/assets/8960296/19215319/7ff18bdc-8d92-11e6-80d9-badf9015b955.png)

**An edge case (notice the dots after)** 
![screen shot 2016-10-08 at 8 02 58 pm](https://cloud.githubusercontent.com/assets/8960296/19215316/6f75996a-8d92-11e6-8663-84118b426577.png)

**... and again**
![screen shot 2016-10-08 at 8 03 12 pm](https://cloud.githubusercontent.com/assets/8960296/19215317/7674efa4-8d92-11e6-825b-97022a8802e8.png)

**Comment by jslirola** [comment]
Hello, do you have a demo to check it online? It's probably it can be solved in `/config/pagination.php`

**Comment by pjhampton** [comment]
Hey @jslirola!!

No, this is a starter theme so it's not deployed anywhere, without my knowledge. I recommend you install it locally and import this data in: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml

Hope this helps 😄
