### ISSUE TITLE
Add Bootstrap classes to Password Form

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#38]
We need to add `.form-control` and `.btn .btn-primary` to the password protection form.

![screen shot 2016-10-09 at 1 09 06 pm](https://cloud.githubusercontent.com/assets/8960296/19220274/99e9e6a8-8e21-11e6-85be-dd21e4333f5f.png)

Step 1 in this link might help:

https://code.tutsplus.com/articles/customizing-and-styling-the-password-protected-form--wp-22375

**Getting Started**
Set up the theme in your `wp-content` directory. Activate it. Create a Post and protect it. View it from the front-end.

**Comment by lexf** [comment]
Hi, I will take this.

**Comment by Bobeta** [comment]
I can help you out with this one 👍

**Comment by lexf** [comment]
@Bobeta yeah, no problem. You can publish it.

**Comment by Bobeta** [comment]
@lexf Thanks, I just pushed it, feel free to comment or make some changes 👍

**Comment by pjhampton** [comment]
Thanks @Bobeta!! 💛  I will review your PR now. Can you please update your PR message to say: References: #38 ?

I really appreciate the interest @lexf. I can reserve a future issue for you if you want?

**Comment by lexf** [comment]
@pjhampton It will be great, thanks.
