### ISSUE TITLE
Add color to .sticky class

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#40]
On line 28 of static/css/app.css, add the background color `#FFEBCD` to the `.sticky` class.

This issue belongs to who claims this first below! **Please do not send a PR unless you are first to claim this issue otherwise it will be rejected and closed!!**

**Comment by obsidianspork** [comment]
Claiming!

**Comment by pjhampton** [comment]
All yours @obsidianspork 💙  💛  💜
