### ISSUE TITLE
Add padding to articles

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#42]
# Welcome 🚀 

**Please note this is a very simple issue reserved for those who haven't contributed to this repo before.** First come first serve. Please comment below to claim the issue. All other attempts to patch this will be closed.

## The Problem

There is not enough padding on the right and left of the article list.

### No padding (How it currently is)
![screen shot 2016-10-11 at 12 07 05 pm](https://cloud.githubusercontent.com/assets/8960296/19268298/9f251b02-8fab-11e6-9286-1b93254897f6.png)

### With padding (How it should be)
![screen shot 2016-10-11 at 12 06 49 pm](https://cloud.githubusercontent.com/assets/8960296/19268309/af3237fa-8fab-11e6-9809-ce1940b287ca.png)

### Working on this issue

- Claim it!
- Download the theme in wp-content/
- Activate the theme
- Import the XML file from https://codex.wordpress.org/Theme_Unit_Test
- Set posts page
- make fix
- Create PR

### Need help?

Ping @pjhampton

**Comment by moritzsternemann** [comment]
Working on it! 😄

**Comment by pjhampton** [comment]
Thanks @moritzsternemann!! All yours 😄

**Comment by moritzsternemann** [comment]
Quick question: Which page is the one you refer to in the problem description?

**Comment by pjhampton** [comment]
Hey @moritzsternemann 

So it's in home.php - the list of all the posts. However, the tweek will need to be made in the **static/css/app.css** file 😄  Hint: Look to the `.articles` class

**Comment by moritzsternemann** [comment]
Fixed in #43 

Thanks for the hint!
I was a little bit confused because the Posts page (Settings->Reading->Posts page) is only displayed if I do not select a page as the Front page (Settings->Reading->Front page). I'm not sure if this is correct behavior according to https://codex.wordpress.org/Creating_a_Static_Front_Page ...
