### ISSUE TITLE
Light styling to comments section

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#44]
# Welcome 🚀 

**Please note this is a issue reserved for those who haven't contributed to this repo before.** First come first serve. Please comment below to claim the issue. All other attempts to patch this will be closed.

## The Problem

There is no styling on the comments section as yet and is a bit too basic for a starter theme. We need to wrap the comments in bootstrap classes.

### No Styling (How it currently is)

![screen shot 2016-10-12 at 9 54 08 am](https://cloud.githubusercontent.com/assets/8960296/19303768/d888cc16-9061-11e6-9dc8-65af441fb88b.png)

### Working on this issue ❤️ 

- Claim it by commenting below!
- Download the theme in wp-content/
- Activate the theme
- Import the XML file from https://codex.wordpress.org/Theme_Unit_Test
- Look at the **Template: Comments** post
- Style comments
- Create PR

### Need help?

Ping @pjhampton

**Comment by VictorAlagwu** [comment]
Will work on it

**Comment by pjhampton** [comment]
You rock @VictorAlagwu!! 💙  

Let me know if you need any help

**Comment by pjhampton** [comment]
Hey @VictorAlagwu. How are you getting on with this? Need any help? 😄

**Comment by pjhampton** [comment]
Closed due to inactivity.
