### ISSUE TITLE
Uncaught Error: Bootstrap tooltips require Tether

### ISSUE THREAD

**Issue by rveitch** [pjhampton/BigBooty#45]
`Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)`

![image](https://cloud.githubusercontent.com/assets/12876929/19336327/ee7fabe8-90cf-11e6-800e-84e225dca772.png)

It looks like the tether.js dependency is missing, I believe it needs to be loaded before bootstrap.js.  I'd also be happy to look into this issue for Hacktoberfest if you wanted to label it.

**Comment by pjhampton** [comment]
Yes, please @rveitch 💯

**Comment by pjhampton** [comment]
Looks like your doing really well @rveitch ~ https://hacktoberfestchecker.herokuapp.com/?username=rveitch

Thanks for all your help. I REALLY appreciate it! 😄
