### ISSUE TITLE
Basic styling for WooCommerce checkout

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#54]
We need to ask basic styling to the form on the check out. Here are screenshots of the checkout in its current state. To claim this issue, please comment below.

![screen shot 2016-10-18 at 7 32 45 pm](https://cloud.githubusercontent.com/assets/8960296/19491471/ff5d520e-956a-11e6-924b-61e4ffde4fe5.png)

![screen shot 2016-10-18 at 7 33 06 pm](https://cloud.githubusercontent.com/assets/8960296/19491476/0706eb0a-956b-11e6-8845-1605f1771a62.png)

**Comment by manuelmdn** [comment]
I'ill work in this

**Comment by pjhampton** [comment]
Awesome @manuelmdn!! 😄

**Comment by pjhampton** [comment]
Hey @manuelmdn! :)

How are you getting on with this? Do you need any help?

**Comment by pjhampton** [comment]
Wow, this looks amazing @manuelmdn 

💙  💛  ❤️  💚

**Comment by manuelmdn** [comment]
Can you create a dev branch?

**Comment by pjhampton** [comment]
Done 😄

**Comment by pjhampton** [comment]
Thanks @manuelmdn 😄  really cool job

**Comment by pjhampton** [comment]
Reopening to push to master
