### ISSUE TITLE
Replace Bootstrap files

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#57]
It seems that Bootstrap recently updated from Bootstrap 4-alpha.4 to Bootstrap 4-alpha.5. It would be good to replace the following files:

  - static/css/bootstrap.min.css
  - static/js/bootstrap.min.js

See the download here: https://v4-alpha.getbootstrap.com/getting-started/download/

This issue is reserved for new-comers to the project! If you are interested in working on this issue, pleas claim it by commenting below. Please do not send an unsolicited pull request.

**Comment by divayprakash** [comment]
@pjhampton Working on it!
