### ISSUE TITLE
Refactor: Moves code to different file

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#64]
We need to move lines 59 - 82 in [functions.php](https://github.com/pjhampton/BigBooty/blob/master/functions.php) into a new file (config/styling.php) and then require that file in functions.php.

This issue is reserved for someone who hasn't yet contributed to this repo. If you are interested in working on this issue, please comment below and send a PR. First come first serve.

**Comment by davelima** [comment]
I'll do it :grin:
