### ISSUE TITLE
Refactor: Moves code to different file

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/BigBooty#66]
We need to move lines 60 - 71 in [functions.php](https://github.com/pjhampton/BigBooty/blob/master/functions.php) into config/styling.php.

This issue is reserved for someone who hasn't yet contributed to this repo. If you are interested in working on this issue, please comment below and send a PR. First come first serve.

**Comment by rishirajjain** [comment]
I'm a newbie can I take this up ?
